version: '3.8'


services:


  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: networking
      POSTGRES_PASSWORD: 951369

      TZ: UTC
    volumes:
      - networking-pg-local:/var/lib/postgresql/data
    ports:
      - "5434:5434"


volumes:
  networking-pg-local:

