spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:netwhiz.cnmiqmq6a7jt.us-east-1.rds.amazonaws.com}:5432/NetWhiz
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:Control-user}

    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"
  cache:
    caffeine:
      spec: expireAfterWrite=60s



logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    org.springframework.jdbc.core: DEBUG # SQL
