name: NetWhiz Backend CICD

on:
    push:
      branches:
        - main
    workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.RAY_DOCKERHUB_USERNAME}} -p ${{secrets.RAY_DOCKERHUB_PASSWORD}}
      - name: Build docker image
        run: docker build -t koway927/netwhiz-backend-cicd .
      - name: Publish image to docker hub
        run: docker push koway927/netwhiz-backend-cicd
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull koway927/netwhiz-backend-cicd
      - name: Delete old container
        run: docker rm -f springbootContainer
      - name: Run docker container
        run: docker run -d -p 8081:8081 --name springbootContainer koway927/netwhiz-backend-cicd